### ISSUE TITLE
the outputs are exactly the same

### ISSUE THREAD

**Issue by xiejiajia2018** [andrew-r96/BertQuestionGeneration#1]
Hello.
    When I run your code, I try to output the results of the valid dataset. I found that all the results are exactly the same. Is there any key steps that I missed when I ran it?

**Comment by andrearosasco** [comment]
Hi, maybe the model overfitted. With which parameters and for how many epochs did you train it?
Also, there are some changes I had to do to project, but due to university commitments I couldn't. I'll get back to it when I can.
For now, you'd wanna switch to the branch "alt-attention". It has a better performing implementation of the attention mechanism.

**Comment by xiejiajia2018** [comment]
thank you for your reply.
I tried the parameters config.1-5 in README for training, but the generated results are still very similar. At the same time, I also replaced the decoder, but it did not solve the problem.

**Comment by andrearosasco** [comment]
Sorry, those were just my not very successful first experiments. To get good results you have to train it for much more epochs. If the model is too big you can try to use hidden states of dimension 512 and "bert-base"
