### ISSUE TITLE
Using the model

### ISSUE THREAD

**Issue by jacampo** [andrew-r96/BertQuestionGeneration#2]
Hello, i'm trying to learn more about question generation and i find your proyect really interesting. I trained it and it generated a model but now i don't know how to try it to see some results. How can i do that? 
Thanks in advance

**Comment by andrearosasco** [comment]
Sorry for the late replay. If you wanna test it you can run the function `eval` in `/src/run/eval.py` to measure the BLUE score. If you wanna see the generated questions you can give the model an input and get the model's output (it will have the shape [batch_size, dict_size, sentence_len]). Then for each word position you take the most probable word (the index in the dict_size vector with the higher value) and convert it to an actual word using the Bert dictionary. You do that for each word and you have the output question.

It's easier than it sounds and it's actually already coded in  `/src/run/eval.py`. Just take that and modify it so that, instead of  using the output to compute the BLUE score you just print it.
